use std::path::Path;

/// Generate an HTML QC report from dcpdoctor verification results.
pub fn generate_report(dcp_dir: &Path, output_html: &Path) -> i32 {
    let qc = crate::qc::run_qc(dcp_dir);

    let dcp_name = dcp_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Unknown DCP");

    let pass_class = if qc.passed { "pass" } else { "fail" };
    let pass_text = if qc.passed { "PASSED" } else { "FAILED" };

    let mut html = String::new();
    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str(&format!(
        "<title>QC Report — {}</title>\n",
        escape_html(dcp_name)
    ));
    html.push_str("<style>\n");
    html.push_str("body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 2em; background: #f5f5f5; }\n");
    html.push_str(".container { max-width: 900px; margin: 0 auto; background: white; padding: 2em; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\n");
    html.push_str("h1 { margin-top: 0; }\n");
    html.push_str(".pass { color: #2e7d32; }\n");
    html.push_str(".fail { color: #c62828; }\n");
    html.push_str(".summary { display: flex; gap: 2em; margin: 1em 0; }\n");
    html.push_str(".summary-item { padding: 1em; border-radius: 4px; background: #f0f0f0; }\n");
    html.push_str(".error { color: #c62828; }\n");
    html.push_str(".warning { color: #f57f17; }\n");
    html.push_str(".info { color: #1565c0; }\n");
    html.push_str("table { width: 100%; border-collapse: collapse; margin-top: 1em; }\n");
    html.push_str(
        "th, td { padding: 0.5em 1em; text-align: left; border-bottom: 1px solid #e0e0e0; }\n",
    );
    html.push_str("th { background: #fafafa; font-weight: 600; }\n");
    html.push_str("footer { margin-top: 2em; color: #888; font-size: 0.85em; }\n");
    html.push_str("</style>\n</head>\n<body>\n<div class=\"container\">\n");

    html.push_str("<h1>QC Report</h1>\n");
    html.push_str(&format!("<h2>{}</h2>\n", escape_html(dcp_name)));
    html.push_str(&format!(
        "<p class=\"{pass_class}\"><strong>Result: {pass_text}</strong></p>\n"
    ));

    html.push_str("<div class=\"summary\">\n");
    html.push_str(&format!(
        "<div class=\"summary-item\"><strong class=\"error\">{}</strong> Errors</div>\n",
        qc.error_count
    ));
    html.push_str(&format!(
        "<div class=\"summary-item\"><strong class=\"warning\">{}</strong> Warnings</div>\n",
        qc.warning_count
    ));
    html.push_str(&format!(
        "<div class=\"summary-item\"><strong class=\"info\">{}</strong> Info</div>\n",
        qc.info_count
    ));
    html.push_str("</div>\n");

    if !qc.results.is_empty() {
        html.push_str("<table>\n<thead><tr><th>Level</th><th>Code</th><th>Message</th></tr></thead>\n<tbody>\n");

        for result in &qc.results {
            let (level_class, level_text) = match result.level {
                crate::qc::QcLevel::Error => ("error", "Error"),
                crate::qc::QcLevel::Warning => ("warning", "Warning"),
                crate::qc::QcLevel::Info => ("info", "Info"),
            };
            html.push_str(&format!(
                "<tr><td class=\"{level_class}\">{level_text}</td><td>{}</td><td>{}</td></tr>\n",
                escape_html(&result.code),
                escape_html(&result.message)
            ));
        }

        html.push_str("</tbody>\n</table>\n");
    }

    html.push_str("<footer>Generated by DCP Wizard</footer>\n");
    html.push_str("</div>\n</body>\n</html>\n");

    match std::fs::write(output_html, &html) {
        Ok(()) => {
            tracing::info!("Generated QC report: {}", output_html.display());
            0
        }
        Err(e) => {
            tracing::error!("Failed to write report: {e}");
            -1
        }
    }
}

fn escape_html(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
