#include "dcpwizard/report.h"
#include "dcpwizard/info.h"
#include "dcpwizard/qc.h"

#include <filesystem>
#include <fstream>
#include <spdlog/spdlog.h>

namespace fs = std::filesystem;

namespace dcpwizard
{

int generate_report(const fs::path& dcp_dir, const fs::path& output_html)
{
  if (!fs::exists(dcp_dir))
  {
    spdlog::error("DCP not found: {}", dcp_dir.string());
    return 1;
  }

  spdlog::info("Generating QC report for: {}", dcp_dir.string());

  auto info = inspect_dcp(dcp_dir);
  auto qc = run_qc(dcp_dir);

  std::ofstream f(output_html);
  f << "<!DOCTYPE html>\n<html><head>\n";
  f << "<title>DCP QC Report — " << info.title << "</title>\n";
  f << "<style>body{font-family:sans-serif;max-width:900px;margin:2em auto;padding:0 1em}";
  f << "table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:8px}";
  f << ".pass{color:green;font-weight:bold}.fail{color:red;font-weight:bold}";
  f << ".warn{color:orange}</style>\n</head><body>\n";
  f << "<h1>DCP QC Report</h1>\n";
  f << "<h2>" << info.title << "</h2>\n";

  f << "<table>\n";
  f << "<tr><td><strong>Standard</strong></td><td>" << info.standard << "</td></tr>\n";
  f << "<tr><td><strong>Resolution</strong></td><td>" << info.resolution << "</td></tr>\n";
  f << "<tr><td><strong>Frame Rate</strong></td><td>" << info.frame_rate << "</td></tr>\n";
  f << "<tr><td><strong>Duration</strong></td><td>" << info.duration_frames << " frames</td></tr>\n";
  f << "<tr><td><strong>Reels</strong></td><td>" << info.reel_count << "</td></tr>\n";
  f << "<tr><td><strong>Encrypted</strong></td><td>" << (info.encrypted ? "Yes" : "No") << "</td></tr>\n";
  f << "<tr><td><strong>Total Size</strong></td><td>" << (info.total_size_bytes / (1024*1024)) << " MB</td></tr>\n";
  f << "</table>\n";

  f << "<h3>QC Result: <span class=\"" << (qc.passed ? "pass" : "fail") << "\">";
  f << (qc.passed ? "PASS" : "FAIL") << "</span></h3>\n";

  if (!qc.results.empty())
  {
    f << "<table><tr><th>Level</th><th>Code</th><th>Message</th><th>Location</th></tr>\n";
    for (const auto& r : qc.results)
    {
      std::string cls = (r.level == QCLevel::Error) ? "fail" : (r.level == QCLevel::Warning) ? "warn" : "";
      std::string lvl = (r.level == QCLevel::Error) ? "ERROR" : (r.level == QCLevel::Warning) ? "WARN" : "INFO";
      f << "<tr><td class=\"" << cls << "\">" << lvl << "</td>";
      f << "<td>" << r.code << "</td><td>" << r.message << "</td><td>" << r.location << "</td></tr>\n";
    }
    f << "</table>\n";
  }

  f << "<p><em>Generated by dcpwizard</em></p>\n";
  f << "</body></html>\n";

  spdlog::info("Report written: {}", output_html.string());
  return 0;
}

} // namespace dcpwizard
